"""Add scores to user

Revision ID: 5c7b2431c8af
Revises: 
Create Date: 2025-05-06 00:15:21.883585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c7b2431c8af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_locations_id_location'), 'locations', ['id_location'], unique=False)
    op.create_index(op.f('ix_room_rounds_id'), 'room_rounds', ['id'], unique=False)
    op.alter_column('rooms', 'guest_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('(true)'))
    op.alter_column('rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index('code', table_name='rooms')
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True)
    op.create_index(op.f('ix_rooms_id_room'), 'rooms', ['id_room'], unique=False)
    op.add_column('users', sa.Column('solo_score', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('multi_score', sa.Integer(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index('email', table_name='users')
    op.drop_index('nickname', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('nickname', 'users', ['nickname'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('users', 'multi_score')
    op.drop_column('users', 'solo_score')
    op.drop_index(op.f('ix_rooms_id_room'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.create_index('code', 'rooms', ['code'], unique=True)
    op.alter_column('rooms', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('rooms', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('(true)'))
    op.alter_column('rooms', 'guest_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_room_rounds_id'), table_name='room_rounds')
    op.drop_index(op.f('ix_locations_id_location'), table_name='locations')
    # ### end Alembic commands ###
