"""add total_rounds to solo_rooms

Revision ID: 5dcc8945e15f
Revises: 49bc086091f3
Create Date: 2025-05-06 07:41:43.225598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcc8945e15f'
down_revision: Union[str, None] = '49bc086091f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('solo_rooms', sa.Column('total_rounds', sa.Integer(), nullable=True))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solo_rounds', 'total_rounds')
    # ### end Alembic commands ###
