"""Add total_score to SoloRoom

Revision ID: c63cb71d500d
Revises: 5dcc8945e15f
Create Date: 2025-05-06 08:28:37.344784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63cb71d500d'
down_revision: Union[str, None] = '5dcc8945e15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('solo_rooms', sa.Column('total_score', sa.Integer(), nullable=False))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solo_rooms', 'total_score')
    # ### end Alembic commands ###
